tosca_definitions_version: cloudify_dsl_1_0

imports:
  - http://www.getcloudify.org/spec/cloudify/3.2/types.yaml
  - https://raw.githubusercontent.com/kemiz/tosca-vcloud-plugin/master/plugin.yaml

inputs:

  catalog:
    type: string
    default: 'giga'

  template:
    type: string

  server_cpu:
    default: 2
    description: >
      cpu count for each server

  server_memory:
    default: 4096
    description: >
      memory amount for each server

  username:
    description: >
      User for connecting to agent VM's
    type: string
    default: 'Admin'

  password:
    description: >
      Password for connecting to agent VM's
    type: string
    default: '123'

<<<<<<< HEAD
  server_name:
    type: string
    default: 'windows-server'

=======
>>>>>>> origin/3.2
node_types:

  windows.nodes.Server:
    derived_from: cloudify.vcloud.nodes.WindowsServer
    properties:
      cloudify_agent:
        default:
          user: { get_input: username }
          password: { get_input: password }
      server:
        default:
          name: { get_input: server_name }
          userdata: |
            #ps1_sysnative
            winrm quickconfig -q
            winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
            winrm set winrm/config '@{MaxTimeoutms="1800000"}'
            winrm set winrm/config/service '@{AllowUnencrypted="true"}'
            winrm set winrm/config/service/auth '@{Basic="true"}'
            &netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
            &netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow

            msiexec /i https://www.python.org/ftp/python/2.7.6/python-2.7.6.msi TARGETDIR=C:\Python27 ALLUSERS=1 /qn
            
          catalog: { get_input: catalog }
          template: { get_input: template }
          hardware:
            cpu: { get_input: server_cpu }
            memory: { get_input: server_memory }
          guest_customization:
              computer_name: { get_input: server_name }
              admin_password: { get_input: password }    

node_templates:

  windows_host:
    type: windows.nodes.Server

